tidy

diff --git a/mag/Makefile b/mag/Makefile
--- a/mag/Makefile
+++ b/mag/Makefile
@@ -1,26 +1,34 @@
 PROJECT_NAME := tt_um_mattvenn_r2r_dac
-.PHONY: lvs magic
+MAGIC_RC := $(PDK_ROOT)/sky130A/libs.tech/magic/sky130A.magicrc
+
+.PHONY: lvs magic start
 
 magic:
-	magic -rcfile sky130A.magicrc $(PROJECT_NAME).mag
+	magic -rcfile $(MAGIC_RC) $(PROJECT_NAME).mag
 
-$(PROJECT_NAME).lvs.spice:
-	magic -noconsole -dnull extract_forlvs.tcl
+tt_block_1x2_pg_ana.def:
+	# https://github.com/TinyTapeout/tt-support-tools/blob/tt06/def/analog/tt_block_1x2_pg_ana.def
+	wget https://raw.githubusercontent.com/TinyTapeout/tt-support-tools/tt06/def/analog/tt_block_1x2_pg_ana.def
+
+start: tt_block_1x2_pg_ana.def
+	magic -rcfile $(MAGIC_RC) -noconsole -dnull tcl/tt-analog-draw.tcl $(PROJECT_NAME)
+
+$(PROJECT_NAME).lvs.spice: $(PROJECT_NAME).mag
+	magic -noconsole -dnull tcl/extract_for_lvs.tcl $(PROJECT_NAME)
 	rm -f *.ext
 
+drc:
+	magic -noconsole -dnull tcl/drc.tcl $(PROJECT_NAME)
+	
 extract_sim:
-	magic -noconsole -dnull extract_forsim.tcl
+	magic -noconsole -dnull tcl/extract_for_sim.tcl $(PROJECT_NAME)
 	rm -f *.ext
 
-extractr2r_sim:
-	magic -noconsole -dnull extract_r2r_forsim.tcl
-	rm -f *.ext
-
-lvs.report: $(PROJECT_NAME).lvs.spice
-	netgen -batch source full_lvs.netgen
+lvs.report: $(PROJECT_NAME).lvs.spice ../src/project.v
+	netgen -batch eval "set project $(PROJECT_NAME) ; source tcl/lvs_netgen.tcl"
 
 lvs: lvs.report
-	@propOk=1; match=0; \
+	@propOk=1; match=0; port=1; \
     if grep -q "match uniquely" lvs.report; then \
         match=1; \
     fi; \
@@ -30,17 +38,26 @@ lvs: lvs.report
     if grep -q "Final result: Netlists do not match" lvs.report; then \
         match=0; \
     fi; \
-    if grep -q "Final result: Circuits match uniquely" lvs.report; then \
+    if grep -q "Final result: Netlists do not match" lvs.report; then \
+        match=0; \
+    fi; \
+    if grep -q "port errors" lvs.report; then \
+        port=0; \
+    fi; \
+    if grep -q "Final result: Circuits match uniquely\." lvs.report; then \
         match=1; \
     fi; \
-	if [ $$match -eq 1 ] && [ $$propOk -eq 1 ]; then \
+	if [ $$match -eq 1 ] && [ $$propOk -eq 1 ] && [ $$port -eq 1 ]; then \
         echo "LVS OK"; \
+	    exit 0; \
     else \
-        echo "LVS FAIL: match $$match properties $$propOk"; \
+        echo "LVS FAIL: match=$$match properties=$$propOk port=$$port"; \
+	    exit 1; \
     fi
 
 update_gds:
-	magic -noconsole -dnull rexport.tcl
+	mkdir -p ../gds ../lef
+	magic -noconsole -dnull tcl/update_gds_lef.tcl $(PROJECT_NAME)
 
 clean:
-	rm lvs.report $(PROJECT_NAME).lvs.spice
+	rm -f lvs.report $(PROJECT_NAME).lvs.spice
